"""Names for every element cut out of the source sheets.

Order matches the detection reading order (top-to-bottom rows, left-to-right
inside a row) verified against the annotated sheets in tools/_analysis.
Names describe the role the element plays in the app, not just its artwork.
"""

# Sheets that stay intact. Value is the destination path inside assets/ui.
WHOLE_ASSETS: dict[str, str] = {
    "main_circus_background_asset": "backdrop/stage_curtains",
    "circus_arena_asset": "backdrop/arena",
    "final_show_illustration_asset": "backdrop/finale_stage",
    "circus_spotlight_asset": "object/spotlight",
    "performance_ribbon_asset": "object/ribbon",
    "performance_blueprint_card_asset": "object/blueprint_card",
    "vintage_circus_poster_asset": "object/playbill",
    "golden_theater_frame_asset": "object/theater_frame",
    "Game_Name": "brand/logotype",
    "Vertical_Loading_Screen": "splash/portrait",
    "Horizontal_Loading_Screen": "splash/landscape",
}

# Sheets that get sliced. Keys are sheet stems, values are element names in
# detection order; the count must match exactly or the export aborts.
SET_ASSETS: dict[str, list[str]] = {
    # Trick disciplines used by the Trick Library and Sequence Builder.
    "trick_category_icons_set_asset": [
        "trick/acrobatics",
        "trick/cards",
        "trick/magic",
        "trick/stage",
    ],
    # Routine preparation stages: Draft, Planning, Rehearsal, Ready, Completed.
    "Performance_Status_Icons_Set_asset": [
        "status/draft",
        "status/planning",
        "status/rehearsal",
        "status/ready",
        "status/completed",
    ],
    "Rehearsal_Checklist_Icons_Set_asset": [
        "checklist/music",
        "checklist/costume",
        "checklist/props",
        "checklist/lighting",
        "checklist/stage",
        "checklist/safety",
    ],
    "Stage_Equipment_Icons_Set_asset": [
        "equipment/fresnel_light",
        "equipment/microphone",
        "equipment/music",
        "equipment/costume",
        "equipment/curtain",
        "equipment/pedestal",
        "equipment/profile_light",
    ],
    "circus_emblems_set_asset": [
        "emblem/joker",
        "emblem/mask",
        "emblem/cards",
        "emblem/tent",
    ],
    "golden_ornaments_set_asset": [
        "ornament/crest_tent",
        "ornament/crest_star",
        "ornament/crest_mask",
        "ornament/crest_shell",
    ],
    "circus_stage_decorations_set_asset": [
        "decor/curtains",
        "decor/column",
        "decor/lantern",
        "decor/podium",
    ],
    # Frames for the Cue Card System.
    "card_frames_set_asset": [
        "cue_frame/curtain",
        "cue_frame/tent",
        "cue_frame/jester",
        "cue_frame/stripes",
    ],
    "paper_textures_set_asset": [
        "paper/aged",
        "paper/sunburst",
        "paper/linen",
        "paper/ticket",
    ],
    "Script_Planner_Pages_Set_asset": [
        "page/lined",
        "page/blocks",
        "page/grid",
        "page/schedule",
        "page/landscape",
    ],
    "Progress_Tracking_Elements_Set_asset": [
        "progress/bar_crimson",
        "progress/bar_emerald",
        "progress/bar_paper",
        "progress/steps_crimson",
        "progress/steps_emerald",
        "progress/check_crimson",
        "progress/check_crimson_bold",
        "progress/check_laurel",
        "progress/check_wreath",
        "progress/check_swoosh",
        "progress/check_scallop",
        "progress/shield_lyre",
        "progress/shield_mask",
        "progress/shield_curtain",
        "progress/shield_light",
        "progress/shield_quill",
        "progress/rosette_crimson",
        "progress/rosette_emerald",
        "progress/rosette_cream",
        "progress/seal_crimson",
        "progress/seal_emerald",
        "progress/pin_star",
        "progress/pin_drape",
        "progress/pin_crown",
        "progress/pin_feather",
        "progress/pin_lyre",
        "progress/pin_mask",
        "progress/badge_star",
        "progress/badge_drape",
        "progress/badge_light",
        "progress/badge_laurel",
    ],
    "Performance_Timeline_Elements_Set_asset": [
        "timeline/pin_curtain",
        "timeline/pin_swag",
        "timeline/pin_masks",
        "timeline/pin_star",
        "timeline/pin_tassel",
        "timeline/pin_fireworks",
        "timeline/divider_plain",
        "timeline/divider_beads",
        "timeline/divider_diamonds",
        "timeline/divider_ornate",
        "timeline/card_curtain",
        "timeline/card_tent",
        "timeline/card_spotlight",
        "timeline/card_fireworks",
        "timeline/card_chandelier",
        "timeline/card_bigtop",
        "timeline/pennant_curtain",
        "timeline/pennant_swag",
        "timeline/pennant_masks",
        "timeline/pennant_star",
        "timeline/pennant_tassel",
        "timeline/pennant_fireworks",
        "timeline/ornament_fleur",
        "timeline/ornament_bar_dot",
        "timeline/ornament_scroll",
        "timeline/ornament_bar_thin",
        "timeline/ornament_star",
        "timeline/tassel_gold",
        "timeline/tassel_crimson",
        "timeline/tassel_black",
        "timeline/tassel_emerald",
        "timeline/flourish_wide",
        "timeline/flourish_small",
        "timeline/drape_crimson",
        "timeline/drape_black",
        "timeline/drape_emerald",
    ],
}

SOUNDS: dict[str, str] = {
    "app_launch_theatrical_chord_asset": "launch_chord",
    "card_flip_sound_asset": "card_flip",
    "magic_element_click_asset": "tap",
    "performance_save_stamp_asset": "save_stamp",
    "screen_transition_curtain_asset": "transition",
    "show_completion_finale_asset": "finale",
    "success_bell_chime_asset": "success",
    "theatrical_error_note_asset": "error",
}
